---

- name: base configuration for all hosts
  hosts: homelab
  become: true

  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "/home/ansible/.ssh/ansible_key"

  tasks:
    - include_tasks: tasks/update_packages.yml
    - include_tasks: tasks/base_config.yml
 #   - include_tasks: tasks/user_accounts.yml
 #   - include_role: name=install_packages

- name: configure docker hosts
  hosts: docker_hosts
  become: true

  vars:
    ansible_user: ansible

  tasks:
    - include_tasks: tasks/install_docker.yaml
